services:
  app:
    image: mysocietyorg/stringprint2:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/stringprint_document_source/
      - ./_conf/config.yaml:/workspaces/stringprint_document_source/stringprint2/proj/conf/config.yaml
    working_dir: /workspaces/stringprint_document_source/
    ports:
      - ${PORT:-8000}:8000
    environment:
      GDRIVE_SERVICE_USER: ${GDRIVE_SERVICE_USER}
      MYSOCIETY_TOKEN: ${MYSOCIETY_TOKEN}
      UNSPLASH_CLIENT_ID: ${UNSPLASH_CLIENT_ID}
