file_source: document.md
cite_as: Parsons, Alex
description: Arguments about equal constituencies are also arguments about different ways of being represented
title: 'Equal seats, unequal voters: The gap between numerical and political representation'
display_footnotes_at_foot: true
sections_over_pages: false
display_notes: false
display_toc: false
short_title: Equal Seats
pdf: Equal seats, unequal voters.pdf
header:
  location: george-pagan-iii-WwCTFNpZx8g-unsplash.jpg
  size: 6
byline: Alex Parsons
publish_date: 2020-07-15
authors: Alex Parsons
seed: -1
