file_source: document.md
cite_as: Parsons, Alex
description: How do we reconcile 'One Person, One Vote' with natural communities?
title: 'Drawing Lines on Maps: Arguments about Political Boundaries'
display_footnotes_at_foot: true
sections_over_pages: false
display_notes: false
display_toc: false
short_title: Drawing Lines
pdf: drawing lines on maps.pdf
header:
  location: 25804358301_866d3e718e_k_AtN93Dx.jpg
  size: 6
byline: Alex Parsons
publish_date: 2016-09-22
authors: Alex Parsons
seed: 13
