file_source: document.md
cite_as: Parsons, Alex
description: Six requirements for making all voters equal in elections.
title: 'Criteria for political equality: Reframing Still’s 1981 criteria'
display_footnotes_at_foot: true
sections_over_pages: false
display_notes: false
display_toc: false
short_title: Political Equality
pdf: criteria-for-political-equality.pdf
header:
  location: andrew-ridley-jR4Zf-riEjI-unsplash.jpg
  size: 6
byline: Alex Parsons
publish_date: 2020-02-16
authors: Alex Parsons
seed: -1
